### ISSUE TITLE
Set Background null object reference

### ISSUE THREAD

**Issue by mwaqarfarooqui** [AliAzaz/AndroidValidatorCrawler#2]
Facing this issue. 
![ISSUE](https://user-images.githubusercontent.com/42797209/72345969-c6008900-36f6-11ea-8c76-57850582db1c.PNG)

**Comment by AliAzaz** [comment]
resolved this in 1.0.1 Release

**Comment by mwaqarfarooqui** [comment]
Ok.

**Comment by mwaqarfarooqui** [comment]
Yes its working.
