### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by ahs1n** [AliAzaz/AndroidValidatorCrawler#3]
I'm getting a validation issue. The scenario is: I have a form containing nested views. The issue is happening when I'm using Clear view class to clear and set enabled false to all downside views as it's working fine but when I'm doing validation on this View it's giving me validation error on radiogroup. The screenshot is attached:
![screenshot_2020-04-20-13-10-33](https://user-images.githubusercontent.com/39263745/79730121-cc139080-8309-11ea-957a-009041731651.png)

**Comment by AliAzaz** [comment]
Thanks for submitting the issue. Let me check this scenario.

**Comment by AliAzaz** [comment]
Hy @ahs1n I fixed the issue and released the build. Do check it and let me know it's working fine or not. I would also appreciate PRs from your side.

**Comment by AliAzaz** [comment]
Is it resolved in your case or not??

**Comment by ahs1n** [comment]
It resolved thank you Ali

**Comment by AliAzaz** [comment]
Got it. I'm closing this issue.
